"""Delegate read-only queries to a hub running on another machine over SSH.

Motivation: the machine that aggregates sessions (always-on, does the rsync +
ingest on a timer) is usually not the laptop you type on. Rather than copying
a multi-GB hub.db around, query commands are forwarded to the hub host and only
the rendered output comes back.

Only read-only commands are forwarded. Commands that reconfigure or mutate a
hub (init, add-host, sync, ingest, run, service, uninstall) always execute
locally, so a stray `sessionhub service uninstall` can never take down the
remote hub by accident.
"""

from __future__ import annotations

import os
import shlex
import subprocess
import sys

from sessionhub.config import Config, RemoteQuery

# Commands safe to run against a remote hub.
FORWARDABLE = frozenset(
    {"recent", "list", "search", "show", "raw", "stats", "status", "tag"}
)

# Commands needing an interactive terminal on the far end (they page output).
NEEDS_TTY = frozenset({"raw"})


def resolve(cfg: Config | None, host_flag: str | None, local_flag: bool) -> RemoteQuery | None:
    """Decide which remote hub to query, if any.

    Precedence: --local  >  --remote HOST  >  $SESSIONHUB_REMOTE  >  config.
    """
    if local_flag:
        return None

    configured = cfg.remote_query if cfg else None
    host = host_flag or os.environ.get("SESSIONHUB_REMOTE")
    if not host:
        return configured

    bin_path = os.environ.get("SESSIONHUB_REMOTE_BIN")
    if not bin_path and configured and configured.host == host:
        # Naming the host you already configured must not throw away the
        # binary path found for it — that path is the whole reason remote
        # queries work on a host with a bare non-interactive PATH.
        bin_path = configured.bin
    return RemoteQuery(host=host, bin=bin_path)


def build_command(rq: RemoteQuery, argv: list[str]) -> list[str]:
    """Build the ssh argv that runs `sessionhub <argv>` on the remote host."""
    # Each argument is quoted individually: the remote shell would otherwise
    # re-split them, breaking multi-word queries like: search "split brain".
    quoted = " ".join(shlex.quote(a) for a in argv)

    if rq.bin:
        # Absolute path — no PATH lookup, no login shell needed.
        remote_cmd = f"{shlex.quote(rq.bin)} {quoted}"
    else:
        # Fall back to a login shell so the remote profile puts sessionhub
        # (often in ~/.local/bin) on PATH. Non-interactive SSH does not.
        remote_cmd = "bash -lc " + shlex.quote(f"sessionhub {quoted}")

    ssh = ["ssh"]
    if argv and argv[0] in NEEDS_TTY:
        ssh.append("-t")
    # --local guards against a misconfigured remote pointing back at itself.
    ssh += [rq.host, remote_cmd]
    return ssh


def run(rq: RemoteQuery, argv: list[str]) -> int:
    """Forward argv to the remote hub. Returns its exit code."""
    cmd = build_command(rq, argv)
    try:
        return subprocess.run(cmd).returncode
    except FileNotFoundError:
        print("ssh not found on PATH.", file=sys.stderr)
        return 127
    except KeyboardInterrupt:
        return 130


SHIM_TEMPLATE = """#!/usr/bin/env bash
# Generated by `sessionhub remote install`.
# Queries the sessionhub hub on {display_host} instead of the local database.
exec {exe} --remote {quoted_host} "$@"
"""


def shim_source(host: str, exe: str | None = None) -> str:
    """A one-line wrapper around `sessionhub --remote <host>`.

    The absolute path of the interpreter's own sessionhub is baked in: the
    shim is typically called from shells whose PATH lacks ~/.local/bin, and
    "command not found" is a miserable way to learn that.
    """
    if exe is None:
        from sessionhub.service import resolve_exe

        exe = resolve_exe()
    # The comment shows the plain host; only executed words are quoted.
    return SHIM_TEMPLATE.format(
        display_host=host,
        quoted_host=shlex.quote(host),
        exe=exe if " " in exe else shlex.quote(exe),
    )
